from enum import Enum

class Action(Enum):
    PAUSE_AND_ESCALATE = "PAUSE_AND_ESCALATE"
    NO_ACTION = "NO_ACTION"
    SEND_PAYMENT_LINK = "SEND_PAYMENT_LINK"
    SEND_PAYMENT_REMINDER = "SEND_PAYMENT_REMINDER"
    SCHEDULE_PAYMENT_REMINDER = "SCHEDULE_PAYMENT_REMINDER"
    UPDATE_PAYMENT_METHOD = "UPDATE_PAYMENT_METHOD"
    SEND_FAILURE_EXPLANATION = "SEND_FAILURE_EXPLANATION"
    REVIEW = "REVIEW"

    