from enum import Enum
 

class Intent(Enum):
    READY_TO_PAY = "READY_TO_PAY"
    PAYMENT_DELAY = "PAYMENT_DELAY"
    UPDATE_PAYMENT_METHOD = "UPDATE_PAYMENT_METHOD"
    PAYMENT_FAILURE_QUERY = "PAYMENT_FAILURE_QUERY"
    DECLINED  = "DECLINED"
    UNKNOWN = "UNKNOWN"
